### PR TITLE
Add login mutation template in gateway

### PR DESCRIPTION
**Pull request by micalgenus**

### CODE REVIEW

**Comment by blackcowmooo** [comment]
Frontend: http://moomark-pr-73.kubernetes.micalgenus.com/
Gateway: http://moomark-pr-73-gateway.kubernetes.micalgenus.com/
Gateway.playground: http://moomark-pr-73-gateway.kubernetes.micalgenus.com/graphql
Backend.Redis: http://moomark-pr-73-redis.kubernetes.micalgenus.com/
Backend.RabbitMQ: http://moomark-pr-73-backend-rabbitmq.kubernetes.micalgenus.com/
Backend.Auth: http://moomark-pr-73-backend-auth.kubernetes.micalgenus.com/

**Comment by blackcowmooo** [comment]
Frontend: http://moomark-pr-73.kubernetes.micalgenus.com/
Gateway: http://moomark-pr-73-gateway.kubernetes.micalgenus.com/
Gateway.playground: http://moomark-pr-73-gateway.kubernetes.micalgenus.com/graphql
Backend.Redis: http://moomark-pr-73-redis.kubernetes.micalgenus.com/
Backend.RabbitMQ: http://moomark-pr-73-backend-rabbitmq.kubernetes.micalgenus.com/
Backend.Auth: http://moomark-pr-73-backend-auth.kubernetes.micalgenus.com/

**Comment by blackcowmooo** [comment]
Frontend: http://moomark-pr-73.kubernetes.micalgenus.com/
Gateway: http://moomark-pr-73-gateway.kubernetes.micalgenus.com/
Gateway.playground: http://moomark-pr-73-gateway.kubernetes.micalgenus.com/graphql
Backend.Redis: http://moomark-pr-73-redis.kubernetes.micalgenus.com/
Backend.RabbitMQ: http://moomark-pr-73-backend-rabbitmq.kubernetes.micalgenus.com/
Backend.Auth: http://moomark-pr-73-backend-auth.kubernetes.micalgenus.com/

**Comment by blackcowmooo** [comment]
Frontend: http://moomark-pr-73.kubernetes.micalgenus.com/
Gateway: http://moomark-pr-73-gateway.kubernetes.micalgenus.com/
Gateway.playground: http://moomark-pr-73-gateway.kubernetes.micalgenus.com/graphql
Backend.Redis: http://moomark-pr-73-redis.kubernetes.micalgenus.com/
Backend.RabbitMQ: http://moomark-pr-73-backend-rabbitmq.kubernetes.micalgenus.com/
Backend.Auth: http://moomark-pr-73-backend-auth.kubernetes.micalgenus.com/

**Comment by blackcowmooo** [comment]
Frontend: http://moomark-pr-73.kubernetes.micalgenus.com/
Gateway: http://moomark-pr-73-gateway.kubernetes.micalgenus.com/
Gateway.playground: http://moomark-pr-73-gateway.kubernetes.micalgenus.com/graphql
Backend.Redis: http://moomark-pr-73-redis.kubernetes.micalgenus.com/
Backend.RabbitMQ: http://moomark-pr-73-backend-rabbitmq.kubernetes.micalgenus.com/
Backend.Auth: http://moomark-pr-73-backend-auth.kubernetes.micalgenus.com/

**Comment by blackcowmooo** [comment]
Frontend: http://moomark-pr-73.kubernetes.micalgenus.com/
Gateway: http://moomark-pr-73-gateway.kubernetes.micalgenus.com/
Gateway.playground: http://moomark-pr-73-gateway.kubernetes.micalgenus.com/graphql
Backend.Redis: http://moomark-pr-73-redis.kubernetes.micalgenus.com/
Backend.RabbitMQ: http://moomark-pr-73-backend-rabbitmq.kubernetes.micalgenus.com/
Backend.Auth: http://moomark-pr-73-backend-auth.kubernetes.micalgenus.com/

**Comment by blackcowmooo** [comment]
Frontend: http://moomark-pr-73.kubernetes.micalgenus.com/
Gateway: http://moomark-pr-73-gateway.kubernetes.micalgenus.com/
Gateway.playground: http://moomark-pr-73-gateway.kubernetes.micalgenus.com/graphql
Backend.Redis: http://moomark-pr-73-redis.kubernetes.micalgenus.com/
Backend.RabbitMQ: http://moomark-pr-73-backend-rabbitmq.kubernetes.micalgenus.com/
Backend.Auth: http://moomark-pr-73-backend-auth.kubernetes.micalgenus.com/

**Comment by blackcowmooo** [comment]
Frontend: http://moomark-pr-73.kubernetes.micalgenus.com/
Gateway: http://moomark-pr-73-gateway.kubernetes.micalgenus.com/
Gateway.playground: http://moomark-pr-73-gateway.kubernetes.micalgenus.com/graphql
Backend.Redis: http://moomark-pr-73-redis.kubernetes.micalgenus.com/
Backend.RabbitMQ: http://moomark-pr-73-backend-rabbitmq.kubernetes.micalgenus.com/
Backend.Auth: http://moomark-pr-73-backend-auth.kubernetes.micalgenus.com/

**Comment by blackcowmooo** [comment]
Frontend: http://moomark-pr-73.kubernetes.micalgenus.com/
Gateway: http://moomark-pr-73-gateway.kubernetes.micalgenus.com/
Gateway.playground: http://moomark-pr-73-gateway.kubernetes.micalgenus.com/graphql
Backend.Redis: http://moomark-pr-73-redis.kubernetes.micalgenus.com/
Backend.RabbitMQ: http://moomark-pr-73-backend-rabbitmq.kubernetes.micalgenus.com/
Backend.Auth: http://moomark-pr-73-backend-auth.kubernetes.micalgenus.com/

**Comment by blackcowmooo** [comment]
Frontend: http://moomark-pr-73.kubernetes.micalgenus.com/
Gateway: http://moomark-pr-73-gateway.kubernetes.micalgenus.com/
Gateway.playground: http://moomark-pr-73-gateway.kubernetes.micalgenus.com/graphql
Backend.Redis: http://moomark-pr-73-redis.kubernetes.micalgenus.com/
Backend.RabbitMQ: http://moomark-pr-73-backend-rabbitmq.kubernetes.micalgenus.com/
Backend.Auth: http://moomark-pr-73-backend-auth.kubernetes.micalgenus.com/

**Comment by blackcowmooo** [comment]
Frontend: http://moomark-pr-73.kubernetes.micalgenus.com/
Gateway: http://moomark-pr-73-gateway.kubernetes.micalgenus.com/
Gateway.playground: http://moomark-pr-73-gateway.kubernetes.micalgenus.com/graphql
Backend.Redis: http://moomark-pr-73-redis.kubernetes.micalgenus.com/
Backend.RabbitMQ: http://moomark-pr-73-backend-rabbitmq.kubernetes.micalgenus.com/
Backend.Auth: http://moomark-pr-73-backend-auth.kubernetes.micalgenus.com/

**Comment by blackcowmooo** [comment]
Frontend: http://moomark-pr-73.kubernetes.micalgenus.com/
Gateway: http://moomark-pr-73-gateway.kubernetes.micalgenus.com/
Gateway.playground: http://moomark-pr-73-gateway.kubernetes.micalgenus.com/graphql
Backend.Redis: http://moomark-pr-73-redis.kubernetes.micalgenus.com/
Backend.RabbitMQ: http://moomark-pr-73-backend-rabbitmq.kubernetes.micalgenus.com/
Backend.Auth: http://moomark-pr-73-backend-auth.kubernetes.micalgenus.com/

**Comment by blackcowmooo** [comment]
Frontend: http://moomark-pr-73.kubernetes.micalgenus.com/
Gateway: http://moomark-pr-73-gateway.kubernetes.micalgenus.com/
Gateway.playground: http://moomark-pr-73-gateway.kubernetes.micalgenus.com/graphql
Backend.Redis: http://moomark-pr-73-redis.kubernetes.micalgenus.com/
Backend.RabbitMQ: http://moomark-pr-73-backend-rabbitmq.kubernetes.micalgenus.com/
Backend.Auth: http://moomark-pr-73-backend-auth.kubernetes.micalgenus.com/

**Comment by blackcowmooo** [comment]
[Server]
Frontend: http://moomark-pr-73.kubernetes.micalgenus.com/
Gateway: http://moomark-pr-73-gateway.kubernetes.micalgenus.com/
Gateway.playground: http://moomark-pr-73-gateway.kubernetes.micalgenus.com/graphql
Backend.Redis: http://moomark-pr-73-redis.kubernetes.micalgenus.com/
Backend.RabbitMQ: http://moomark-pr-73-backend-rabbitmq.kubernetes.micalgenus.com/
Backend.Auth: http://moomark-pr-73-backend-auth.kubernetes.micalgenus.com/

**Comment by blackcowmooo** [comment]
[Log]
Frontend: http://moomark-pr-73-logger.kubernetes.micalgenus.com/frontend
Gateway: http://moomark-pr-73-logger.kubernetes.micalgenus.com/gateway
Backend.Auth: http://moomark-pr-73-logger.kubernetes.micalgenus.com/backend-auth

**Comment by blackcowmooo** [comment]
[Server]
Frontend: http://moomark-pr-73.kubernetes.micalgenus.com/
Gateway: http://moomark-pr-73-gateway.kubernetes.micalgenus.com/
Gateway.playground: http://moomark-pr-73-gateway.kubernetes.micalgenus.com/graphql
Backend.Redis: http://moomark-pr-73-redis.kubernetes.micalgenus.com/
Backend.RabbitMQ: http://moomark-pr-73-backend-rabbitmq.kubernetes.micalgenus.com/
Backend.Auth: http://moomark-pr-73-backend-auth.kubernetes.micalgenus.com/

**Comment by blackcowmooo** [comment]
[Log]
Frontend: http://moomark-pr-73-logger.kubernetes.micalgenus.com/frontend
Gateway: http://moomark-pr-73-logger.kubernetes.micalgenus.com/gateway
Backend.Auth: http://moomark-pr-73-logger.kubernetes.micalgenus.com/backend-auth

**Comment by blackcowmooo** [comment]
[Server]
Frontend: http://moomark-pr-73.kubernetes.micalgenus.com/
Gateway: http://moomark-pr-73-gateway.kubernetes.micalgenus.com/
Gateway.playground: http://moomark-pr-73-gateway.kubernetes.micalgenus.com/graphql
Backend.Redis: http://moomark-pr-73-redis.kubernetes.micalgenus.com/
Backend.RabbitMQ: http://moomark-pr-73-backend-rabbitmq.kubernetes.micalgenus.com/
Backend.Auth: http://moomark-pr-73-backend-auth.kubernetes.micalgenus.com/
Backend.Notification: http://moomark-pr-73-backend-notification.kubernetes.micalgenus.com/

**Comment by blackcowmooo** [comment]
[Log]
Frontend: http://moomark-pr-73-logger.kubernetes.micalgenus.com/frontend
Gateway: http://moomark-pr-73-logger.kubernetes.micalgenus.com/gateway
Backend.Auth: http://moomark-pr-73-logger.kubernetes.micalgenus.com/backend-auth
Backend.Notification: http://moomark-pr-73-logger.kubernetes.micalgenus.com/backend-notification

**Review by lcc3108 — APPROVED** [review]

**Pull request merged**
