### PR TITLE
Add redis-commander in test (PR)

### PR DESCRIPTION
**Pull request by micalgenus**

### CODE REVIEW

**Comment by blackcowmooo** [comment]
Frontend: http://moomark-pr-45.kubernetes.micalgenus.com/
Gateway: http://moomark-pr-45-gateway.kubernetes.micalgenus.com/
Backend.Auth: http://moomark-pr-45-backend-auth.kubernetes.micalgenus.com/

**Comment by blackcowmooo** [comment]
Frontend: http://moomark-pr-45.kubernetes.micalgenus.com/
Gateway: http://moomark-pr-45-gateway.kubernetes.micalgenus.com/
Backend.Auth: http://moomark-pr-45-backend-auth.kubernetes.micalgenus.com/

**Comment by blackcowmooo** [comment]
Frontend: http://moomark-pr-45.kubernetes.micalgenus.com/
Gateway: http://moomark-pr-45-gateway.kubernetes.micalgenus.com/
Backend.Redis: http://moomark-pr-45-redis.kubernetes.micalgenus.com/
Backend.Auth: http://moomark-pr-45-backend-auth.kubernetes.micalgenus.com/

**Comment by blackcowmooo** [comment]
Frontend: http://moomark-pr-45.kubernetes.micalgenus.com/
Gateway: http://moomark-pr-45-gateway.kubernetes.micalgenus.com/
Backend.Redis: http://moomark-pr-45-redis.kubernetes.micalgenus.com/
Backend.Auth: http://moomark-pr-45-backend-auth.kubernetes.micalgenus.com/

**Comment by blackcowmooo** [comment]
Frontend: http://moomark-pr-45.kubernetes.micalgenus.com/
Gateway: http://moomark-pr-45-gateway.kubernetes.micalgenus.com/
Backend.Redis: http://moomark-pr-45-redis.kubernetes.micalgenus.com/
Backend.Auth: http://moomark-pr-45-backend-auth.kubernetes.micalgenus.com/

**Comment by blackcowmooo** [comment]
Frontend: http://moomark-pr-45.kubernetes.micalgenus.com/
Gateway: http://moomark-pr-45-gateway.kubernetes.micalgenus.com/
Backend.Redis: http://moomark-pr-45-redis.kubernetes.micalgenus.com/
Backend.Auth: http://moomark-pr-45-backend-auth.kubernetes.micalgenus.com/

**Comment by blackcowmooo** [comment]
Frontend: http://moomark-pr-45.kubernetes.micalgenus.com/
Gateway: http://moomark-pr-45-gateway.kubernetes.micalgenus.com/
Backend.Redis: http://moomark-pr-45-redis.kubernetes.micalgenus.com/
Backend.RabbitMQ: http://moomark-pr-45-backend-rabbitmq.kubernetes.micalgenus.com/
Backend.Auth: http://moomark-pr-45-backend-auth.kubernetes.micalgenus.com/

**Comment by blackcowmooo** [comment]
Frontend: http://moomark-pr-45.kubernetes.micalgenus.com/
Gateway: http://moomark-pr-45-gateway.kubernetes.micalgenus.com/
Backend.Redis: http://moomark-pr-45-redis.kubernetes.micalgenus.com/
Backend.RabbitMQ: http://moomark-pr-45-backend-rabbitmq.kubernetes.micalgenus.com/
Backend.Auth: http://moomark-pr-45-backend-auth.kubernetes.micalgenus.com/

**Comment by blackcowmooo** [comment]
Frontend: http://moomark-pr-45.kubernetes.micalgenus.com/
Gateway: http://moomark-pr-45-gateway.kubernetes.micalgenus.com/
Backend.Redis: http://moomark-pr-45-redis.kubernetes.micalgenus.com/
Backend.RabbitMQ: http://moomark-pr-45-backend-rabbitmq.kubernetes.micalgenus.com/
Backend.Auth: http://moomark-pr-45-backend-auth.kubernetes.micalgenus.com/

**Comment by Apisapple** [comment]
leave a comment

**Comment by blackcowmooo** [comment]
Frontend: http://moomark-pr-45.kubernetes.micalgenus.com/
Gateway: http://moomark-pr-45-gateway.kubernetes.micalgenus.com/
Gateway.playground: http://moomark-pr-45-gateway.kubernetes.micalgenus.com/graphql
Backend.Redis: http://moomark-pr-45-redis.kubernetes.micalgenus.com/
Backend.RabbitMQ: http://moomark-pr-45-backend-rabbitmq.kubernetes.micalgenus.com/
Backend.Auth: http://moomark-pr-45-backend-auth.kubernetes.micalgenus.com/

**Pull request merged**
